export const SET_RESOURCES_EN = 'SET_RESOURCES_EN'
export const SET_RESOURCES_FR = 'SET_RESOURCES_FR'
export const TOGGLE_LANGUAGE = 'TOGGLE_LANGUAGE'
export const ADD_SINGLE_RESOURCE = 'ADD_SINGLE_RESOURCE'