export const SET_RESOURCES = 'SET_RESOURCES'
export const RECEIVE_GRANT_DATA = 'RECEIVE_GRANT_DATA'
export const TOGGLE_LANGUAGE = 'TOGGLE_LANGUAGE'
export const ADD_SINGLE_RESOURCE = 'ADD_SINGLE_RESOURCE'